# Generated by Django 5.2.1 on 2025-06-01 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_message_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='index',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
