# Generated by Django 5.2.1 on 2025-06-13 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_message_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='response_time',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
